export * from './AboutSection'
export * from './EducationSection'
export * from './ExperienceSection'
export * from './FeedbackSection'
export * from './FreelanceSection'
export * from './HeroSection'
export * from './ProjectsSection'
export * from './TechSection'